### ISSUE TITLE
Shaarli image: build fail because "index.html" does not exist

### ISSUE THREAD

**Issue by nbedou** [ka2er/docker-files#1]
Thank you for the Shaarli image, it is simple and works great.

However the build fail because of the line `RUN rm index.html` in the `Dockerfile`. The file `index.html` seem to not exist anymore in the `php:5.6-apache` images, then this line is not useful. I guess the automated builds on the hub will work again after this.

Thanks!

**Comment by ka2er** [comment]
Please could you confirm the fix if you have time to test the new build ?

**Comment by nbedou** [comment]
Issue fixed, thanks!
